### ISSUE TITLE
Dhall alternative configuration file

### ISSUE THREAD

**Issue by toastal** [soywod/himalaya#154]
TOML is good, [Dhall](https://dhall-lang.org/) is too (and is [Rust-supported](https://github.com/Nadrieril/dhall-rust)) -- programmable typed configuration.

As a user, I could import configs for GMail, Posteo, et.al. from this repo so the community can share the ports and and host which could lead to easier adoption and onboarding. I would envision the enduser having something like this:

`$XDG_CONFIG_HOME/himalaya/config.dhall`
```dhall
-- adding omittable `: Type` annotations for this example's clarity
-- formatted using `dhall format`, the first-party built-in formatter
-- config files could also be gotten from disk, network is allowable too

-- base config that also re-exports useful types like `Account`
let Config
    : Type
    = https://raw.repo/dhallconfigs/Config.dhall sha:...

-- definitions for the default values for service providers for easier and consistent on-boarding
-- we already host and ports for this provider
let PosteoAccount
    : Config.Account.Type
    = https://raw.repo/dhallconfigs/Accounts/Posteo.dhall sha:...

let GMailAccount
    : Config.Account.Type
    = https://raw.repo/dhallconfigs/Accounts/GMail.dhall sha:...

let posteoEmail
    : Text
    = "user@posteo"

let posteoPasswdCmd
    : Text
    = "pass show posteo"

in    Config::{
      , default-page-size = 100 : Natural
      , accounts =
            [ PosteoAccount::{
              , name = "posteo1"
              , email = posteoEmail
              , imap-login = posteoEmail
              , imap-passwd-cmd = posteoPasswdCmd
              , stmp-login = posteoEmail
              , stmp-passwd-cmd = posteoPasswdCmd
              } // { primary= True }
            -- alternatively a function that can create a compatible `Account.Type`
            , PosteoAccount.create
                { name = "posteo2", email = "user2@posteo.net", passwd-cmd = "pass show posteo2" }
            , GMailAccount::{=} -- etc. with account details
            ]
          : List Config.Account.Type
      }
    : Config.Type
```

a condensed single primary (default) Posteo account could look like (with the rest of the options being default)

```dhall
let Config = https://raw.repo/dhallconfigs/Config.dhall sha:...
let PosteoAccount = https://raw.repo/dhallconfigs/Accounts/Posteo.dhall sha:...
let posteo = PosteoAccount.create { name = "posteo", email = "user@posteo.net", passwd-cmd = "pass show posteo" }
in Config::{ accounts = [ posteo ⫽ { primary = True } ] }
```

and a condensed file for consuming 4 Posteo accounts with a function to consolidate our password commands could look like

```dhall
let List/map = https://prelude.dhall-lang.org/v20.1.0/List/map.dhall sha256:dd845ffb4568d40327f2a817eb42d1c6138b929ca758d50bc33112ef3c885680

let Config = https://raw.repo/dhallconfigs/Config.dhall sha:...

let PosteoAccount = https://raw.repo/dhallconfigs/Accounts/Posteo.dhall sha:...

-- negligible value for a command this short, just an example 
let passShow = \(name : Text) -> "pass show ${name}" 

let accounts
    : List Config.Account.Type
    = List/map { name : Text, email : Text, passwd-cmd : Text }  
        Config.Account.Type
        PosteoAccount.create
        [ { name = "posteo1", email = "user1@posteo.net", passwd-cmd : passShow "user1" }
        , { name = "posteo2", email = "user2@posteo.net", passwd-cmd : passShow "user2" }
        , { name = "posteo3", email = "user3@posteo.net", passwd-cmd : passShow "user3" }
        , { name = "posteo4", email = "user4@posteo.net", passwd-cmd : passShow "user4" }
        ]

in Config::{ accounts }
```

compared to TOML with 4 Posteo accounts (duplicate data not just for this config, but everyone using `himalaya` must go to Posteo to look up what their config options are)

```toml
[posteo1]
email = "user1@posteo.net"
imap-host = "posteo.de"
imap-login = "user1@posteo.net"
imap-passwd-cmd = "pass show posteo"
imap-port = 993
smtp-host = "posteo.de"
smtp-login = "user1@posteo.net"
smtp-passwd-cmd = "pass show posteo"
smtp-port = 465
smtp-starttls = true

[posteo2]
email = "user2@posteo.net"
imap-host = "posteo.de"
imap-login = "user2@posteo.net"
imap-passwd-cmd = "pass show posteo"
imap-port = 993
smtp-host = "posteo.de"
smtp-login = "user2@posteo.net"
smtp-passwd-cmd = "pass show posteo"
smtp-port = 465
smtp-starttls = true

[posteo3]
email = "user3@posteo.net"
imap-host = "posteo.de"
imap-login = "user3@posteo.net"
imap-passwd-cmd = "pass show posteo"
imap-port = 993
smtp-host = "posteo.de"
smtp-login = "user3@posteo.net"
smtp-passwd-cmd = "pass show posteo"
smtp-port = 465
smtp-starttls = true

[posteo4]
email = "user4@posteo.net"
imap-host = "posteo.de"
imap-login = "user4@posteo.net"
imap-passwd-cmd = "pass show posteo"
imap-port = 993
smtp-host = "posteo.de"
smtp-login = "user4@posteo.net"
smtp-passwd-cmd = "pass show posteo"
smtp-port = 465
smtp-starttls = true
```

Advantages I could see: 
- clear default values (just read the default Dhall config, _not_ the Rust source code or the Wiki)
- ability to use `map`, et. al. from the huge [`Prelude`](https://store.dhall-lang.org/Prelude-v20.1.0/) to create a bunch of accounts to remove duplication
- community repo to share and maintain configs for account hosts (as opposed to hardcoding some providers into the source, they can be always-overridable definitions at the config layer)
- this same shared account config could also in theory be used by other projects (remapping keys if necessary), or have configs shared by the provider (Welcome to CoolPrivateMail™. To use our service with `himalaya` just import our account config and you can always be up-to-date with our latest configs so you don't even have to think about it!)
- nothing stops users from creating their own useful types
- ability to use ADTs and enums instead of strings in the future
- better data modeling be creating enforcing types like `accounts` requiring one and only one primary account similar to a `NonEmptyList` (requiring no runtime check since multiple primary (default) accounts is now impossible to construct)
  ```dhall
  let Accounts : Type =
    { primary = Account.Type
    , additional = List Account.Type
    }
  ``` 
- clearer errors (the TOML errors for `watch-cmds` being renamed was useless and wasted my time telling me `invalid length 1, expected struct Account with 19 elements at line 7 column 1` instead of warning me about the offending top-level key)
- support the small-but-growing Dhall community

Disadvantages:
- maintaining two configuration types and what to prioritize
- users may not want to learn this new language (although I had to brush up on TOML because it's not common for me; I would not call it easy nor did the error messages help as much as I would have liked)
- making breaking changes to `config.toml` to unify the configuration to be ergonomic in both like a `List Account.Type` to describe accounts instead of keys on the top-level record
- reliance on `dhall-rust` staying up-to-date
- if `dhall-to-toml` ever comes to life this could be moot (though I don't think it's even roadmap'd)

I have never used Rust, but I would happily write the Dhall types if this proposition was seen as a positive move.
