### ISSUE TITLE
Could not append message to `Sent`

### ISSUE THREAD

**Issue by TornaxO7** [soywod/himalaya#172]
So I'm testing some stuff currently and when I tried `himalaya write`, this happened:
```
Could not append message to `Sent`
 ↳ No Response: Folder doesn't exist. (Failure)
```
But: If I look into my gmail account, I cann see my mail under the `Send` mailbox. So doesn't that mean that this error message is wrong?

This is my `~/.config/himalaya/config.toml`:
```toml
name = "Sambalakuja"
downloads-dir = "~/"
default-page-size = 50
signature = "I use Arch btw"
watch-cmds = ["mbsync -a"]

[gmail]
default = true
email = "Sambalakuja@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "sambalakuja@gmail.com"
imap-passwd-cmd = "pass show sambalakuja@gmail.com"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "sambalakuja@gmail.com"
smtp-passwd-cmd = "pass show sambalakuja@gmail.com"
```

**Comment by soywod** [comment]
It may be because of the `~` in the `downloads-dir`. As described in the wiki, you need to put the full abs path. See also #102.

**Comment by TornaxO7** [comment]
I changed it to this:
```toml
name = "Sambalakuja"
downloads-dir = "/home/tornax/Downloads"
default-page-size = 50
signature = "I use Arch btw"
watch-cmds = ["mbsync -a"]

[gmail]
default = true
email = "Sambalakuja@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "sambalakuja@gmail.com"
imap-passwd-cmd = "pass show sambalakuja@gmail.com"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "sambalakuja@gmail.com"
smtp-passwd-cmd = "pass show sambalakuja@gmail.com"
```
But the error still exists.
