### ISSUE TITLE
Previous Page goes to another account

### ISSUE THREAD

**Issue by igbanam** [soywod/himalaya#215]
Hi @soywod,

Amazing job on Himalaya 🎉 

I was using the Vim front, and realized when I `gp` from the first page of a non-default account, it lists the emails from my default account. I'd expect it stays within the same account…?

### How to reproduce

With a `config.toml` similar to 

```toml
[first]
default = true
email = first@example.com

[second]
email = second@example.com
```

1. Open Vim (in my case, Neovim)
2. Check the second mailbox with `:Himalaya second`
3. From the mail list view, `gp`
