### ISSUE TITLE
Error: cannot find account "true"

### ISSUE THREAD

**Issue by austintraver** [soywod/himalaya#249]
Possibly related to https://github.com/soywod/himalaya/issues/167

I'm on the most recent version of Himalaya and I'm having trouble getting mailbox preview to work within the most recent version of NeoVim. It's worth noting, however, that I'm a new user of this project, and never used mailbox preview prior to now, so I'm not sure what is causing the issue. Here is an image of the error message that I am seeing when I try to preview my Gmail account's mailboxes on macOS.

<img width="1596" alt="screenshot 121" src="https://user-images.githubusercontent.com/25112463/139431466-ac4f5055-96a1-4e88-8c20-bdaaeabb50a3.png">

I isolated the problem to [this section of `account_entity.rs`](https://github.com/soywod/himalaya/blob/b7d068c7293e3c86f3d7eeb1c0dd64d79ed4fc81/src/config/account_entity.rs#L72-L89). I'd fix it myself but I'm not sure exactly how to do so. Otherwise, I would have submit the pull-request myself.

Any idea what might be causing the problem?

---

For reference, here is my config file

```toml
name = "Austin Traver"
downloads-dir = "~/Downloads"
signature = "redacted"

[gmail]
default = true
email = "redacted@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "redacted@gmail.com"
imap-passwd-cmd = "redacted"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "redacted@gmail.com"
smtp-passwd-cmd = "redacted"
```
