### ISSUE TITLE
Unable to parse status response

### ISSUE THREAD

**Issue by andreivolt** [soywod/himalaya#269]
`mailboxes` works fine though, so authentication is set up correctly and works, but otherwise get this error - and nothing extra with `--log-level trace`

**Comment by jrogers512** [comment]
`$  cat ~/.config/himalaya/config.toml
# https://github.com/soywod/himalaya/wiki/Configuration:config-file

name = "J Rogers"
downloads-dir = "/home/jrogers/Downloads"
signature = """
--
Regards,
"""

[gmail]
default = true
email = "jrogers512@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "jrogers512@gmail.com"
imap-passwd-cmd = "pass show gmail"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "jrogers512@gmail.com"
smtp-passwd-cmd = "pass show gmail"

$ himalaya
Error: cannot select mailbox "INBOX"

Caused by:
    Unable to parse status response

$ himalaya --version
himalaya 0.5.1`

Same issue?  Fresh install, first time using (trying) himalaya

**Comment by soywod** [comment]
It may be because of the name of the inbox mailbox. The default one is `INBOX`, but I'm pretty sure it is not the case on gmail. Could you check please the name of your inbox mailbox with the command `himalaya mbox`?

**Comment by andreivolt** [comment]
Is is named INBOX in Gmail as well.

I get the same error with other mailboxes as well.

**Comment by soywod** [comment]
I can't reproduce with my gmail account:

```toml
# ~/.config/himalaya/config.toml

[gmail]
email = "clement.douin@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "clement.douin@gmail.com"
imap-passwd-cmd = "pass show gmail"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "clement.douin@gmail.com"
smtp-passwd-cmd = "pass show gmail"
```

```bash
himalaya -a gmail mbox

DELIM │NAME              │ATTRIBUTES               
/     │Archives          │\HasNoChildren           
/     │Drafts            │\HasNoChildren           
/     │INBOX             │\HasNoChildren           
/     │Sent              │\HasNoChildren           
/     │Trash             │\HasNoChildren           
/     │[Gmail]           │\HasChildren, NoSelect   
/     │[Gmail]/Bin       │\HasNoChildren, \Trash   
/     │[Gmail]/Drafts    │\Drafts, \HasNoChildren  
/     │[Gmail]/Sent Mail │\HasNoChildren, \Sent    
/     │[Gmail]/Spam      │\HasNoChildren, \Junk    
/     │[Gmail]/Starred   │\Flagged, \HasNoChildren 
```

And the `himalaya -a gmail list` works as expected for me. Could you share the result of your `himalaya mbox`?
