### ISSUE TITLE
Error Parsing Config File When Configuring a Particular Server

### ISSUE THREAD

**Issue by Balrrach** [soywod/himalaya#333]
Hello.

When configuring my working mail server himalaya prompts the following error: 
```
Error: cannot parse config file

Caused by:
    data did not match any variant of untagged enum DeserializedAccountConfig at line 24 column 1
```
Line 24 is the line where my working server configuration starts. If I write the configuration of only my secondary mail which is gmail it all goes well but if I try to include my working server config it fails. 

Also, when copying example config from the wiki I get the exact same error but this time on line 56 which corresponds to `[posteo-local.mailboxes]`.

**Comment by soywod** [comment]
Can you share your full config? It looks like you miss some piece of config.

**Comment by Balrrach** [comment]
Sure, my config is:
```toml
name = "Name"
downloads-dir = "~/Downloads"
signature = "Sincerely, Name"
default-page-size = 50
watch-cmds = ["mbsync -a"]

[gmail]
default = true
email = "name@gmail.com"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "name@gmail.com"
smtp-passwd-cmd = "echo name.passwd"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "name@gmail.com"
imap-passwd-cmd = "echo name.passwd"

[gmail.mailboxes]
sent = "[Gmail]/Sent Mail"
draft = "[Gmail]/Drafts"


[ugr]
default = true
email = "name@correo.ugr.es"

smtp-host = "smtp.ugr.es"
smtp-port = 587
smtp-starttls = true
smtp-login = "name@correo.ugr.es"
smtp-passwd-cmd = "echo name.passwd"

imap-host = "imap.ugr.es"
imap-port = 993
smtp-starttls = false
imap-login = "name@correo.ugr.es"
imap-passwd-cmd = "echo name.passwd"
```

**Comment by soywod** [comment]
The problem comes from the `ugr` account:

```toml
imap-host = "imap.ugr.es"
imap-port = 993
smtp-starttls = false # <<<<<<<<<<<<<<<<<<<<<<<<<< here, you left smtp-startls instead of imap-starttls
imap-login = "name@correo.ugr.es"
imap-passwd-cmd = "echo name.passwd"
```

I agree that the error message is not so friendly, it is because of the way the deserializer has been used inside Himalaya. To make it more clear, I will have to introduce a breaking change (which I would like to avoid for now). I keep it in mind for the `v1` migration guide!
