### ISSUE TITLE
Subject column too small when stdout is redirected

### ISSUE THREAD

**Issue by segfault4** [soywod/himalaya#337]
stdout not redirected:
```
$ TERM=dumb himalaya list

ID │FLAGS │SUBJECT                                                           │SENDER                                       │DATE
15 │      │Important policy updates coming to Discord                        │Discord                                      │2022-03-02 18:53:29
14 │      │Discord Password Changed                                          │Discord                                      │2022-02-23 08:00:53
13 │      │Password Reset Request for Discord                                │Discord                                      │2022-02-23 07:58:40
12 │      │A new feature for your sharings                                   │Claude de Cozy 'claude at cozycloud.cc'      │2022-02-18 11:55:31
11 │      │Welcome to Facebook                                               │Facebook                                     │2022-02-17 05:09:35
```
stdout redirected:
```
$ TERM=dumb himalaya list | awk 'NR>2'
15 │      │Impo… │Discord                                      │2022-03-02 18:53:29
14 │      │Disc… │Discord                                      │2022-02-23 08:00:53
13 │      │Pass… │Discord                                      │2022-02-23 07:58:40
12 │      │A ne… │Claude de Cozy 'claude at cozycloud.cc'      │2022-02-18 11:55:31
11 │      │Welc… │Facebook                                     │2022-02-17 05:09:35
```
config file:
```
name = "segv"
downloads-dir = "/tmp/temp"

[disroot]
default-page-size = 99999
default = true
email = "segv@disroot.org"
imap-host = "disroot.org"
imap-port = 993
imap-login = "segv"
imap-passwd-cmd = "pass segv-disroot"
smtp-host = "disroot.org"
smtp-port = 587
smtp-login = "segv"
smtp-passwd-cmd = "pass segv-disroot"
```
version:
```
$ himalaya -V
himalaya 0.5.8
```

**Comment by soywod** [comment]
Can you try to activate the flowed format?

```toml
[my-account.format]
type = "flowed"
```

**Comment by segfault4** [comment]
it won't works
```
$ cat ~/.config/himalaya/config.toml
name = "segv"
downloads-dir = "/tmp/temp"

[disroot]
default-page-size = 99999
default = true
email = "segv@disroot.org"
imap-host = "disroot.org"
imap-port = 993
imap-login = "segv"
imap-passwd-cmd = "pass segv-disroot"
smtp-host = "disroot.org"
smtp-port = 587
smtp-login = "segv"
smtp-passwd-cmd = "pass segv-disroot"
type = "flowed"%
$ himalaya list | cat

ID │FLAGS │SUBJ… │SENDER                                       │DATE
15 │      │Impo… │Discord                                      │2022-03-02 18:53:29
14 │      │Disc… │Discord                                      │2022-02-23 08:00:53
13 │      │Pass… │Discord                                      │2022-02-23 07:58:40
12 │      │A ne… │Claude de Cozy 'claude at cozycloud.cc'      │2022-02-18 11:55:31
11 │      │Welc… │Facebook                                     │2022-02-17 05:09:35
10 │      │Face… │Facebook                                     │2022-02-17 05:09:29
```

**Comment by soywod** [comment]
You misplaced the `type` property, please check the [wiki](https://github.com/soywod/himalaya/wiki/Configuration:config-file#account-config), the `type` property expects a hash map:

```toml
[disroot]
default-page-size = 99999
default = true
email = "segv@disroot.org"
imap-host = "disroot.org"
imap-port = 993
imap-login = "segv"
imap-passwd-cmd = "pass segv-disroot"
smtp-host = "disroot.org"
smtp-port = 587
smtp-login = "segv"
smtp-passwd-cmd = "pass segv-disroot"

[disroot.format]
type = "flowed"
```

or

```toml
[disroot]
default-page-size = 99999
default = true
email = "segv@disroot.org"
imap-host = "disroot.org"
imap-port = 993
imap-login = "segv"
imap-passwd-cmd = "pass segv-disroot"
smtp-host = "disroot.org"
smtp-port = 587
smtp-login = "segv"
smtp-passwd-cmd = "pass segv-disroot"
format = { type = "flowed" }
```
