### ISSUE TITLE
[Question] setup with pass and sync

### ISSUE THREAD

**Issue by timsofteng** [soywod/himalaya#350]
Hello.
I want to try Himalaya but I don't know how to setup it properly.
I want to put passes with gnu pass.
How can I fill gpg password in gpg-agent and run Himalaya to watch my accounts and send notifications?

**Comment by soywod** [comment]
Did you check the [wiki](https://github.com/soywod/himalaya/wiki/Configuration:config-file)? You have full of resources that could help you building your config file. You even have an example with `pass`:

```toml
name = "Your Name"

[you-account-name]
default = true
email = "your@email.com"

smtp-host = "your@smtp.com"
smtp-port = 465
smtp-login = "your@email.com"
smtp-passwd-cmd = "pass show gmail"

imap-host = "your@imap.com"
imap-port = 993
imap-login = "your@email.com"
imap-passwd-cmd = "pass show gmail"
```

Feel free to open a [discussion](https://github.com/soywod/himalaya/discussions) if you still cannot run Himalaya on your own.
