### ISSUE TITLE
Sync error: cannot fetch from uid 1

### ISSUE THREAD

**Issue by rudolfvesely** [soywod/himalaya#453]
Dear Clément,

Thank you for the fantastic open-source you're developing. Himalaya is a great tool.

I configured Himalaya to get e-mail from proton.me (protonmail) bridge like this:

``` toml
display-name = ...
downloads-dir = ...
signature = ...
email-listing-page-size = 50

["mymail@example.com"]
default = true
sync = true
sync-folders-strategy.exclude = ["All Mail", "Starred"]
display-name = "None"
email = "mymail@example.com"
backend = "imap"
imap-host = "127.0.0.1"
imap-insecure = true
imap-ssl = true
imap-starttls = true
imap-port = 1143
imap-login = "mymail@example.com"
imap-auth = "passwd"
imap-passwd.raw = ...
imap-notify-cmd = """📫 "<sender>" "<subject>"""
imap-notify-query = "NOT SEEN"
imap-watch-cmds = ["echo \"received server changes!\""]
sender = "smtp"
smtp-host = "127.0.0.1"
smtp-insecure = true
smtp-ssl = true
smtp-starttls = true
smtp-port = 1025
smtp-login = "mymail@example.com"
smtp-auth = "passwd"
smtp-passwd.raw = ...
```

And I added 3 accounts to the Bridge (the configuration above is identical for all 3 accounts except e-mail address and password).

I successfully run `himalaya --account mymail@example.com account sync` for 2 accounts but the 3rd account gave me:

~~~
Error: cannot fetch imap emails within uid range 1:*

Caused by:
    Bye Response: no explanation given
~~~

The error very self-explanatory (== great message) since the 3rd account has a lot of expunged e-mails - specifically previous years that I archived.

To make sure this is not an issue with the Bridge, I run `isync` (`mbsync`) on the 3rd account and it successfully copied all e-mails to Maildir.

Please let me know if you need any additional details or more testing.

Thank you for reading the issue and for fantastic Himalaya.

Kind regards,

Rudolf Vesely
