### ISSUE TITLE
Cannot login to IMAP server

### ISSUE THREAD

**Issue by orhun** [soywod/himalaya#52]
Hey!

I have a config file as following:

```toml
name = "CMF"
downloads-dir = "/home/orhun/downloads"
signature = "Regards,\nCMF"

[gmail]
default = true
email = "coolmodfiles@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "coolmodfiles@gmail.com"
imap-passwd-cmd = "echo <password>"

smtp-host = "smtp.gmail.com"
smtp-port = 487
smtp-login = "coolmodfiles@gmail.com"
smtp-passwd-cmd = "echo <password>"
```

(I'm pretty sure my password is correct)

But when I run `himalaya`, I get the following error:

```
Cannot login to IMAP server
 ↳ No Response: [AUTHENTICATIONFAILED] Invalid credentials (Failure)
```

Also I get a mail on my other gmail accounts that there was a login attempt and it was prevented. Although I confirm that "it was me", I still cannot login with `himalaya`.

Do I have to tweak some kind of setting on gmail and maybe allow login from 3rd party apps somewhere? I couldn't see anything about that on the wiki.
