### ISSUE TITLE
Cannot login to IMAP server

### ISSUE THREAD

**Issue by nbouliol** [soywod/himalaya#72]
Hi !

I have this error :

```bash
❯ himalaya
Cannot login to IMAP server
 ↳ No Response: Empty username or password.
```

And this is my config file :

```toml
name = "Nicolas Bouliol"
downloads-dir = "~/himalaya"
signature = "Regards,"


[gmail]
default = true
email = "cheuveux@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "cheuveux@gmail.com"
imap-passwd-cmd = ""

smtp-host = "smtp.gmail.com"
smtp-port = 487
smtp-login = "cheuveux@gmail.com"
smtp-passwd-cmd = ""
```

`imap-passwd-cmd` and `smtp-passwd-cmd` are generated passwords as mentionend in #52 

What did I miss ?
